// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarClothing.Admin.Api.Infrastructure;

namespace StellarClothing.Admin.Api.Migrations
{
    [DbContext(typeof(AdminContext))]
    [Migration("20200214102456_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.FooterMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FooterMenus");
                });

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.HeadingMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasChildren");

                    b.Property<byte>("ItemColumn");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<byte>("Parent");

                    b.HasKey("Id");

                    b.ToTable("HeadingMenus");
                });

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<short>("PollId");

                    b.Property<int?>("PollId1");

                    b.HasKey("Id");

                    b.HasIndex("PollId1");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Question");

                    b.HasKey("Id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.SliderPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alt");

                    b.Property<int>("SliderId");

                    b.Property<string>("Source");

                    b.HasKey("Id");

                    b.HasIndex("SliderId");

                    b.ToTable("SliderPhotos");
                });

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OptionId");

                    b.Property<DateTime>("Time");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.Option", b =>
                {
                    b.HasOne("StellarClothing.Admin.Api.Domain.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId1");
                });

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.SliderPhoto", b =>
                {
                    b.HasOne("StellarClothing.Admin.Api.Domain.Slider", "Slider")
                        .WithMany("SliderPhotos")
                        .HasForeignKey("SliderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StellarClothing.Admin.Api.Domain.Vote", b =>
                {
                    b.HasOne("StellarClothing.Admin.Api.Domain.Option", "Option")
                        .WithMany("Votes")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
